# Generated by Django 3.0.5 on 2021-05-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210415_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Contact2')),
            ],
        ),
    ]
