# Generated by Django 3.0.5 on 2021-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_abc_contact2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='contact',
        ),
        migrations.AddField(
            model_name='abc',
            name='contact',
            field=models.ManyToManyField(to='home.Contact2'),
        ),
    ]
