# Generated by Django 3.0.5 on 2021-05-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210509_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abc',
        ),
        migrations.DeleteModel(
            name='Contact2',
        ),
    ]
